### ISSUE TITLE
add "concepts" to 'rtfm'

### ISSUE THREAD

**Issue by ghost** [Voxel-Fox-Ltd/Apple.Py#101]
I'll make the docs if you need some

**Comment by 4Kaylum** [comment]
This is too vague an issue to keep open while there's nowhere to search - I'm closing this unless you can give me a relevant documentation URL to look into.

**Comment by ghost** [comment]
> This is too vague an issue to keep open while there's nowhere to search - I'm closing this unless you can give me a relevant documentation URL to look into.

https://betterprogramming.pub/archive?source=post_page-----227ed5dc2b4b--------------------------------

https://softwareontheroad.com/

https://levelup.gitconnected.com/

**Comment by 4Kaylum** [comment]
> https://betterprogramming.pub/archive?source=post_page-----227ed5dc2b4b--------------------------------

This is a Medium website - it's better than your other links in terms of searchability, but Medium itself doesn't actually have a search API. In addition, this website is far from comprehensive. 

> https://softwareontheroad.com/

I literally can't even find where on the website to list all their articles. I doubt they have an accessible API.

> https://levelup.gitconnected.com/

This, again, is another list of articles rather than a reference of something. It's another Medium website as well, so it has the same issues as listed in point 1.

It seems a lot like you're just trying to find _articles_ rather than a _reference_, which is what the `rtfm` command is meant to represent.
