### ISSUE TITLE
For `stealemoji`, if an image given is larger than 256KB, try to compress/resize it

### ISSUE THREAD

**Issue by iHeroGH** [Voxel-Fox-Ltd/Apple.Py#149]

**Comment by 4Kaylum** [comment]
`f(n) = n * h * w * c = s` where `n` is the size modifier, `h` is the image height, `w` is the image width, and `c` is the magic "I will turn you into a PNG" constant, and `s` is the image's filesize in bytes.

What we do to find out a value for `n` where `s` is lower than or equal to 256,000?

`nhwc = s` -> `nc = s/hw` so where `n` is 1, `c = s/hw` to give us a `c`. We can then use that to work out a compression ratio: `n = 256,000/hwc`.

Unfortunately, this doesn't match up to reality. I tried this myself and got an image 40KB smaller than calculated, due to how PNGs get compressed. This _is_ something I could do for the bot but I would likely overshoot the compression ratio to be even smaller than 256KB, if that's an issue.

**Comment by iHeroGH** [comment]
I would rather an inaccurate compression than having to compress it manually in a photo editing program. It could be a setting or an extra boolean parameter in the command or something, if it's that much of an issue.
