### ISSUE TITLE
Use timestamp formatters for `whois`

### ISSUE THREAD

**Issue by sn8to** [Voxel-Fox-Ltd/Apple.Py#212]

**Comment by 4Kaylum** [comment]
Not doing this until they're implemented on all platforms.

**Comment by sn8to** [comment]
They're on the stable desktop/web client (at least for me) and the iOS client. I don't own an Android device so I don't know if it's implemented there.

**Comment by 4Kaylum** [comment]
Well hey, turns out they work. I'll get this into vbu as something first and then come back to it here. 

![Screenshot_20210706-025702_Discord.jpg](https://user-images.githubusercontent.com/5342536/124531203-f3b72180-de05-11eb-9213-cedd7a3c9ed1.jpg)

**Comment by sn8to** [comment]
That's what I was thinking. At first I was going to PR the change, but my brain is slightly too small to make a proper timestamp formatting util.

**Comment by Silverdimond** [comment]
This issue was resolved in https://github.com/Voxel-Fox-Ltd/Apple.Py/commit/1cd299f53a11546c1729c553f80e4c041dea4add#diff-1079472eafb98d71cbc33b7affc14df9821a0b0f02b9fff9d4acd13598058979R43  
![image](https://user-images.githubusercontent.com/46320280/190730101-55d52eb4-3e60-432b-b125-512b6a13d687.png)    
It should be closed
